AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template

Resources:
  HelloWorldFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: HelloWorld
      Handler: org.noframework.Handler # for documentation only, has no effect.
      Runtime: provided
      MemorySize: 2048
      CodeUri: .
    Metadata:
      BuildMethod: makefile
