/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.noframework;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Bootstrap classUnderTest = new Bootstrap();
        assertNotNull("constructor passes", classUnderTest);
    }
}
